### ISSUE TITLE
Need any help?

### ISSUE THREAD

**Issue by nivekithan** [Mokshit06/premix#1]
Hey I came to know about your project from `kcd` discord.

I just want to let you know I am available for any kind of collaboration on this project if you need anything.

I do have experience with `react`. But when it comes to `backend` and `ssr` I dont have any experience at all ( I  just recently started to explore it)

Also I dont have license to `remix`

**Comment by Mokshit06** [comment]
Hey @nivekithan, I am not looking for any collaborations on this project right now. I will let you know if and when I am looking for collaborations. If you want to try out premix, you can clone the repository and look [here](https://github.com/Mokshit06/premix/tree/main/docs) for docs
